#! /usr/bin/perl -w
use strict;
use warnings;
use Gtk2 '-init';
use Greenend::ViewGCOV::AnnotatedFile;
use Greenend::ViewGCOV::Window;

# Command line ----------------------------------------------------------------

while(@ARGV > 0 and $ARGV[0] =~ /^-/) {
    my $opt = shift;
    if($opt eq "--help") {
        print
"Usage:
  viewgcov [OPTIONS] [--] [DIRECTORY]

Options:
  --help       Display usage message

Displays gcov output files below DIRECTORY (default=".").
";
        exit 0;
    } elsif($opt eq "--") {
        last;
    } else {
        die "ERROR: unknown option '$_'\n";
    }
}

# Create the UI ---------------------------------------------------------------

my $window = new Greenend::ViewGCOV::Window();

# Fill in initial files -------------------------------------------------------

my $directory = ".";
if(@ARGV > 0) {
    $directory = shift;
    die "ERROR: specify at most one directory\n" if @ARGV > 0;
}
die "ERROR: $directory is not readable\n" 
    if !-r $directory or !-x $directory;
die "ERROR: $directory is not a directory\n" 
    if !-d $directory;
$window->{files}->setDirectory($directory);

# Run the UI ------------------------------------------------------------------

$window->widget()->show_all();
Gtk2->main();
